areas:
  1:  # This is the ID of the drop area (must be a number, used to link with schedules.yml and commands)
    world: world  # The name of the world where loot drops should spawn
    x1: -100      # First X coordinate of the square area
    z1: -100      # First Z coordinate of the square area
    x2: 100       # Second X coordinate of the square area
    z2: 100       # Second Z coordinate of the square area
    interval: 300 # If not using scheduled drops, this is the interval (in seconds) between each automatic drop
    sync: false   # If true, this area's drops happen in sync with other areas that also have sync: true
    lootTable:    # The loot table for this area: item material names mapped to drop probability (0.0 to 1.0)
      DIAMOND: 0.1
      IRON_SWORD: 0.3
      BREAD: 0.8

  2:
    world: world      # Another area in the same or different world
    x1: 200
    z1: 200
    x2: 300
    z2: 300
    interval: 600     # This value only matters if not using the schedule system
    sync: true        # This area's drops will happen at the same time as other sync: true areas
    lootTable:
      GOLDEN_APPLE: 0.05
      COOKED_BEEF: 0.7
      ARROW: 0.6
